# name: Node.js CI

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js 16
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
#     - run: npm install
#     - run: npm run json-server
#     - run: npm start
#     - run: npm run build
    
name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm run json-server
    - run: npm start
    - run: npm run build
